# Generated by Django 4.2.20 on 2025-03-16 08:02

from django.db import migrations, models
import django.db.models.deletion

def link_notification_to_sentence(apps, schema_editor):
    Notification = apps.get_model('vr_app', 'NotificationSettings')
    Sentence = apps.get_model('vr_app', 'Sentence')
    
    for notification in Notification.objects.all():
        # 기존 user 연결을 통해 Sentence 생성
        sentence, _ = Sentence.objects.get_or_create(
            user=notification.user.user,  # 기존 관계 활용
            content="[시스템 생성] 알림용 기본 문장",
            defaults={'is_ai_generated': True}
        )
        notification.sentence = sentence
        notification.save() # sentence의 기본값에 null이들어가면 오류가 발생할 수 있기에 각 문장에 기본 알람설정 함수를 넣어둔다. 

class Migration(migrations.Migration):

    dependencies = [
        ('vr_app', '0002_alter_notificationsettings_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationsettings',
            name='user',
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='sentence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vr_app.sentence'),
        ),
    ]
