# Generated by Django 4.2.20 on 2025-03-16 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vr_app', '0003_remove_notificationsettings_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationsettings',
            name='sentence',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vr_app.sentence'),
            preserve_default=False,
        ),
    ]
