# Generated by Django 4.2.20 on 2025-03-16 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vr_app', '0004_alter_notificationsettings_sentence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='tts_voice',
        ),
        migrations.RemoveField(
            model_name='ttsvoice',
            name='language',
        ),
        migrations.RemoveField(
            model_name='ttsvoice',
            name='style',
        ),
        migrations.AddField(
            model_name='sentence',
            name='tts_voice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vr_app.ttsvoice'),
        ),
        migrations.AddField(
            model_name='ttsvoice',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
