# Generated by Django 4.2.20 on 2025-03-17 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vr_app', '0005_remove_customuser_tts_voice_remove_ttsvoice_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ttsvoice',
            name='language',
            field=models.CharField(default='ko-KR', max_length=10),
        ),
        migrations.AddField(
            model_name='ttsvoice',
            name='voice_id',
            field=models.CharField(default=1, max_length=100, verbose_name='서비스 ID'),
        ),
    ]
