# Generated by Django 4.2.20 on 2025-03-18 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vr_app', '0006_ttsvoice_language_ttsvoice_voice_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationsettings',
            name='sentence',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vr_app.sentence'),
        ),
    ]
