# Generated by Django 4.2.20 on 2025-03-20 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vr_app', '0007_alter_notificationsettings_sentence'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsettings',
            name='is_triggered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='next_notification',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
