# Generated by Django 4.2.20 on 2025-03-22 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vr_app', '0010_fcmtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='fcm_token',
        ),
    ]
