# Generated by Django 4.2.20 on 2025-03-24 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0019_alter_periodictasks_options'),
        ('vr_app', '0011_remove_customuser_fcm_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsettings',
            name='periodic_task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_celery_beat.periodictask'),
        ),
    ]
