# Generated by Django 4.2.20 on 2025-04-04 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vr_app', '0012_notificationsettings_periodic_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_logged_in',
            field=models.BooleanField(default=False),
        ),
    ]
